// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqVqu3DSDp4tbAdmwq4dWVonMUnl_-uc',
    appId: '1:83418604449:web:26d121fd88e51c60ab61e0',
    messagingSenderId: '83418604449',
    projectId: 'apostas-o-retorno-430604',
    authDomain: 'apostas-o-retorno-430604.firebaseapp.com',
    storageBucket: 'apostas-o-retorno-430604.appspot.com',
    measurementId: 'G-MMNCW8ET0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLzpRVD6I6TMYW05F4HSXejnG1RFonqI',
    appId: '1:83418604449:android:0c42c5cf776bfa3fab61e0',
    messagingSenderId: '83418604449',
    projectId: 'apostas-o-retorno-430604',
    storageBucket: 'apostas-o-retorno-430604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRECzBankRKcFb9fzuQeK-z9XY5pb54k',
    appId: '1:83418604449:ios:ee0b87d7c8250e72ab61e0',
    messagingSenderId: '83418604449',
    projectId: 'apostas-o-retorno-430604',
    storageBucket: 'apostas-o-retorno-430604.appspot.com',
    iosBundleId: 'com.example.flutterBetsTheReturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRECzBankRKcFb9fzuQeK-z9XY5pb54k',
    appId: '1:83418604449:ios:ee0b87d7c8250e72ab61e0',
    messagingSenderId: '83418604449',
    projectId: 'apostas-o-retorno-430604',
    storageBucket: 'apostas-o-retorno-430604.appspot.com',
    iosBundleId: 'com.example.flutterBetsTheReturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqqVqu3DSDp4tbAdmwq4dWVonMUnl_-uc',
    appId: '1:83418604449:web:89abff543179cde7ab61e0',
    messagingSenderId: '83418604449',
    projectId: 'apostas-o-retorno-430604',
    authDomain: 'apostas-o-retorno-430604.firebaseapp.com',
    storageBucket: 'apostas-o-retorno-430604.appspot.com',
    measurementId: 'G-RP8WLJYEX1',
  );

}